[package]
name = "CPI-CALCULATOR"
version = "0.1.0"
edition = "2021"
authors = ["Sridhar Tuli <sridhartuli@gmail.com>"]

[dependencies]
egui = "0.27.2"
eframe = "0.27.2"
egui_extras = "0.27.2"
lazy_static = "1.4.0"